### PR TITLE
Added Functions Query and Function Score Query

### PR DESCRIPTION
**Pull request by janaculenova**
Hi, I asked for weight function and function_score with multiple fields few weeks ago.

- Added Functions Query with weight function (it's  possible add more functions)
- Added Function Score Query

### CODE REVIEW

**Comment by erichard** [comment]
Hi ! Thanks for the PR and sorry for the delayed review :pray: 

Can you add some tests please ?

**Comment by janaculenova** [comment]
Sure! I'm a bit busy these days, but I'll try dedicate some day next week.

**Comment by janaculenova** [comment]
Hi @erichard I commited tests

**Comment by erichard** [comment]
Thanks @janaculenova 🙏

**Pull request merged**
