### PR TITLE
Added wildcard filter

### PR DESCRIPTION
**Pull request by StarveTheEgo**
This is my first PR ever, hope it is well-formed

Not sure about escapeWildcards, - hope it suits fine here! :-)

### CODE REVIEW

**Comment by erichard** [comment]
Nice ! Can you add the factory method in `src/Filter/Filter.php` as well ?

**Comment by StarveTheEgo** [comment]
Oh, forgot

**Comment by StarveTheEgo** [comment]
Done! :-)

**Comment by StarveTheEgo** [comment]
Added setSource method also... Not sure if it should be in another branch tho
I need this method too :-D

**Comment by erichard** [comment]
Thanks ! And congrats for your first PR :)

**Pull request merged**
