### PR TITLE
Added in GeoShape Query

### PR DESCRIPTION
**Pull request by byt3sage**
Hi,
I've added in a GeoShape query with a testcase. Also, I'd like to look at maintaining this package if that is possible?

### CODE REVIEW

**Comment by erichard** [comment]
Hi,

Thanks for your PR.

I'm more than welcome to others PR if you have others needs.

**Comment by byt3sage** [comment]
Perfect - I'm just going to bin off the constructor within this class actually - will commit in a minute or two

**Comment by byt3sage** [comment]
That actually works now 😆

**Comment by byt3sage** [comment]
> Perfect - I'm just going to bin off the constructor within this class actually - will commit in a minute or two

So in relation to this - I removed it temporarily until we decide on how to move forward. I've commented on #7

**Comment by byt3sage** [comment]
Closing due to #11

**Pull request closed without merging**
